const names=['level1.jpg','level2.jpg','level3.jpg','level4.jpg','level5.jpg','level6.jpg','level7.jpg','level8.jpg','level9.jpg'];
const imgs=[],cutouts=[];
names.forEach((n,i)=>{const im=new Image();im.onload=()=>cutouts[i]=makeCutout(im);im.src='assets/'+n;imgs[i]=im});
const cvs=document.getElementById('game'),ctx=cvs.getContext('2d'),nextC=document.getElementById('next'),nctx=nextC.getContext('2d');
let W=0,H=0,balls=[],score=0,best=+localStorage.meroBest||0,nextLevel=0,currentLevel=0,gameOver=false,last=0,dangerTime=0;
const radii=[22,29,37,47,59,73,89,108,130];
document.getElementById('best').textContent=best;
function makeCutout(im){const s=document.createElement('canvas'),x=s.getContext('2d');s.width=im.naturalWidth;s.height=im.naturalHeight;x.drawImage(im,0,0);const d=x.getImageData(0,0,s.width,s.height),a=d.data,w=s.width,h=s.height,seen=new Uint8Array(w*h),q=[],corners=[0,w-1,(h-1)*w,h*w-1],cols=corners.map(p=>[a[p*4],a[p*4+1],a[p*4+2]]);for(let p of corners){seen[p]=1;q.push(p)}while(q.length){const p=q.pop(),px=p%w,py=(p/w)|0,r=a[p*4],g=a[p*4+1],b=a[p*4+2],near=cols.some(c=>Math.hypot(r-c[0],g-c[1],b-c[2])<62);if(near)a[p*4+3]=0;else continue;for(const n of [p-1,p+1,p-w,p+w])if(n>=0&&n<w*h&&!seen[n]&&Math.abs((n%w)-px)<=1){seen[n]=1;q.push(n)}}let minX=w,minY=h,maxX=0,maxY=0;for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++)if(a[(y*w+xx)*4+3]>20){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(maxX<=minX)return s;const o=document.createElement('canvas');o.width=maxX-minX+1;o.height=maxY-minY+1;o.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(o.width*o.height*4),o.width,o.height),0,0);o.getContext('2d').drawImage(s,minX,minY,o.width,o.height,0,0,o.width,o.height);return o}
function resize(){const r=cvs.getBoundingClientRect(),d=devicePixelRatio||1;W=r.width;H=Math.max(520,Math.min(760,W*1.52));cvs.width=W*d;cvs.height=H*d;ctx.setTransform(d,0,0,d,0,0)}
function draw(c,x,y,l,p=false){const r=p?Math.min(28,radii[l]*.36):radii[l],im=cutouts[l]||imgs[l];if(im&&im.width){const scale=Math.min(2*r/im.width,2*r/im.height),ww=im.width*scale,hh=im.height*scale;c.drawImage(im,x-ww/2,y-hh/2,ww,hh)}else{c.fillStyle='#d6a553';c.beginPath();c.arc(x,y,r,0,7);c.fill()}c.shadowColor='rgba(90,50,30,.22)';c.shadowBlur=5;c.shadowOffsetY=3}
function showNext(){nctx.clearRect(0,0,64,64);draw(nctx,32,32,nextLevel,true);document.getElementById('level').textContent=Math.min(9,currentLevel+1)}
function reset(){balls=[];score=0;gameOver=false;dangerTime=0;currentLevel=0;nextLevel=Math.floor(Math.random()*4);document.getElementById('score').textContent=0;document.getElementById('hint').style.display='block';showNext();resize()}
function drop(x){if(gameOver)return;const l=nextLevel,r=radii[l];balls.push({x:Math.max(r,Math.min(W-r,x)),y:r+4,vx:0,vy:0,l,r});currentLevel=l;document.getElementById('hint').style.display='none';nextLevel=Math.floor(Math.random()*4);showNext()}
function merge(){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),m=a.r+b.r;if(d<m){if(a.l===b.l){const l=a.l+1,x=(a.x+b.x)/2,y=(a.y+b.y)/2;score+=l*l*10;if(l>=9){balls.splice(j,1);balls.splice(i,1)}else{balls.splice(j,1);balls.splice(i,1);balls.push({x,y,vx:0,vy:-2,l,r:radii[l]})}document.getElementById('score').textContent=score;if(score>best){best=score;localStorage.meroBest=best;document.getElementById('best').textContent=best}return true}const nx=dx/(d||1),ny=dy/(d||1),p=(m-d)/2;a.x-=nx*p;a.y-=ny*p;b.x+=nx*p;b.y+=ny*p}}return false}
function loop(t){const dt=Math.min(2,(t-last)/16||1);last=t;if(!gameOver){for(const b of balls){b.vy+=.32*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r){b.x=b.r;b.vx*=-.35}if(b.x>W-b.r){b.x=W-b.r;b.vx*=-.35}if(b.y>H-b.r){b.y=H-b.r;b.vy*=-.22;b.vx*=.8}}for(let k=0;k<4;k++)merge();if(balls.some(b=>b.y-b.r<52)){dangerTime+=dt}else dangerTime=0;if(dangerTime>60){gameOver=true;setTimeout(()=>alert('Game over! Score: '+score),100)}}ctx.clearRect(0,0,W,H);ctx.strokeStyle='#e5c4ab';ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(0,52);ctx.lineTo(W,52);ctx.stroke();ctx.setLineDash([]);balls.forEach(b=>draw(ctx,b.x,b.y,b.l));requestAnimationFrame(loop)}
function px(e){const r=cvs.getBoundingClientRect();return(e.touches?e.touches[0].clientX:e.clientX)-r.left}
cvs.addEventListener('pointerup',e=>drop(px(e)));document.getElementById('restart').onclick=reset;addEventListener('resize',resize);reset();requestAnimationFrame(loop);function makeCutout(im){const s=document.createElement('canvas'),x=s.getContext('2d');s.width=im.naturalWidth;s.height=im.naturalHeight;x.drawImage(im,0,0);const d=x.getImageData(0,0,s.width,s.height),a=d.data,w=s.width,h=s.height,seen=new Uint8Array(w*h),q=[],corners=[0,w-1,(h-1)*w,w*h-1],cols=corners.map(p=>[a[p*4],a[p*4+1],a[p*4+2]]);for(const p of corners){seen[p]=1;q.push(p)}let removed=0;while(q.length){const p=q.pop(),px=p%w,py=(p/w)|0,r=a[p*4],g=a[p*4+1],b=a[p*4+2],near=cols.some(c=>Math.hypot(r-c[0],g-c[1],b-c[2])<72);if(!near)continue;a[p*4+3]=0;removed++;for(const n of [p-1,p+1,p-w,p+w])if(n>=0&&n<w*h&&!seen[n]&&Math.abs((n%w)-px)<=1){seen[n]=1;q.push(n)}}if(removed<w*h*.08)return im;let minX=w,minY=h,maxX=0,maxY=0,solid=0;for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++)if(a[(y*w+xx)*4+3]>20){solid++;minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(solid<w*h*.08||maxX<=minX||maxY<=minY)return im;const o=document.createElement('canvas');o.width=maxX-minX+1;o.height=maxY-minY+1;o.getContext('2d').putImageData(d,minX,minY);return o}
